### ISSUE TITLE
`ps --no-headers` doesn't work on OSX

### ISSUE THREAD

**Issue by nilsga** [belgattitude/pjbserver-tools#3]
The OSX version of `ps` does not support the `--no-headers` option, which makes it impossible to start and stop the embedded server.

**Comment by belgattitude** [comment]
Hey @nilsga ,

don't have OS/X, let's try another way... I've just replaced the pid running check with a `kill -0`, it might be better.

``` php
$cmd = sprintf("kill -0 %d", $pid);
```

But I have no idea if's gonna work... Could you update to latest master and check with debug enabled (-vvv) ?

``` console
./bin/pjbserver-tools pjbserver:start -vvv ./config/pjbserver.config.php.dist
```

Thanks

**Comment by nilsga** [comment]
`kill -0 <pid>` doesn't yield any output. You might have to throw in a check for a proper exit code instead of parsing the expected output.

**Comment by nilsga** [comment]
Sorry, didn't read rest of the commit. I'll patch the rest manually and try again.

**Comment by nilsga** [comment]
Patch seems to work. Thanks!

**Comment by belgattitude** [comment]
Great !

Before releasing a new version, can you let me know your OSX/Java versions ? 
Just to update the doc. I'm also welcoming any install notes that might help.

Thanks

**Comment by nilsga** [comment]
Thanks. It's OSX Sierra with java `1.8.0_92`. Regarding installation instructions, it would be nice with some pointers how and what to install and run embedded without `composer`. I was planning to use this with Prestashop plugins, and it doesn't support `composer`.

**Comment by nilsga** [comment]
But if you're asking if I had to do something special to install it in addition to the instructions, the answer is no.

**Comment by nilsga** [comment]
That's not entirely correct, when I think of it. It was not clear to me whether the `{base_dir}` and `{tcp_port}` patterns were substituted runtime. But I guess not, since it didn't work leaving them in the config. Also, it didn't seem to allow me to specify `logfile` and `pidfile`, giving errors that the files did not exist.

**Comment by belgattitude** [comment]
Nice, I've added some comments about {base_dir} and {tcp_port}.

Proper creation of `log_file` and `pid_file` is required, could you give me the errors you saw ? There might be something else with  OSX... with the standard config they should have been created in 'pjbserver_tools/var/...' directory after the server started, can you check ?

Many options exists to include the server... the idea is to provide the sources with your plugin, module... For prestashop, you may use composer in your plugin/module directory.. Check [prestashop-install-and-use-vendor-from-composer](http://stackoverflow.com/questions/33679679/prestashop-install-and-use-vendor-from-composer). And publish your module or plugin with the vendor directory. I cannot support this, but can be done with composer in a local context. Otherwise simply copy sources in directory.. and load the files.

But keep in mind that the standalone server is not supposed to play big. Deploying the bridge on Tomcat is best. See the soluble-japha doc.

**Comment by belgattitude** [comment]
Also if you can run phpunit with the latest master on OSX, it's very welcome :)
