### ISSUE TITLE
Custom embedding

### ISSUE THREAD

**Issue by nilsga** [belgattitude/pjbserver-tools#6]
I'm wondering if it is possible to do "custom embedding" of this bridge. So I'm wondering: 
- Where does the jar-file with the servlet "live" (github project? Maven dependency?)?
- What would it take to embed this server into a regular java web application? Is it simply an entry in the web.xml for the servet, or does it take some more setup?

**Comment by belgattitude** [comment]
Hey @nilsga,

A big topic... First of all, the `pjbserver-tools` standalone server was originally made to facilitate unit testing its sister project: the [soluble-japha](https://github.com/belgattitude/soluble-japha) client. 

Basically it allows me to quickly include a simple server on [travis](https://travis-ci.org/belgattitude/soluble-japha) to test the japha client without requiring a tomcat install. I simply do a `composer require soluble/japha belgattitude/pjbserver-tools` to get both installed. The pjbserver-tools, contains already a local copy of the [JavaBridge.jar file](https://github.com/belgattitude/pjbserver-tools/tree/master/resources/pjb621_standalone). I've just compiled it from the [cvs] sourceforge [original repo](https://sourceforge.net/projects/php-java-bridge/). But you can also download binaries on [sourceforge](https://sourceforge.net/projects/php-java-bridge/files/Binary%20package/php-java-bridge_6.2.1/), see the exploded folder for components.

With that, the pjbserver standalone is used for my tests. I have control to [start the server](https://github.com/belgattitude/soluble-japha/blob/master/test/SolubleTestFactories.php#L40), stop it or do everything provided by the API or the config (like add additional jars: mysql-connector,...). In a sense it can be considered as an embed... runnning with minimal deps (only java to start the server).

**Tomcat approach**
On my local machine tests and prod servers, I use exclusively a J2EE approach (easy to interchange from the standalone server). Very solid, no start/stop problems, huge performance and scalability...

I build a .war file with all dependencies I need (the bridge jar, jasper reports...) that I deploy on my Tomcat server, just adding a [web.xml](https://github.com/belgattitude/soluble-japha/blob/master/doc/install_server_j2ee.md). But at this stage I didn't document so much, and I'm aware of the need. The [original bridge server](http://php-java-bridge.sourceforge.net/pjb/) is very solid, but not well documented, neither available on maven central. 

So for now you have some bash scripts [here](https://github.com/belgattitude/pjbserver-tools/blob/master/tools/jasper_bundle_bash/create_jasperbundle_war.sh) that I used at some point. See also the [tools](https://github.com/belgattitude/pjbserver-tools/tree/master/tools) folder. 

**Future**
Not perfect but I would love to make it easier... especially if I can get some help because it's a side project and my free time is very short. Some time ago I migrated the bridge server on [https://github.com/belgattitude/php-java-bridge](https://github.com/belgattitude/php-java-bridge). Could be start to provide some recipes to install based on that repo... CVS on sourceforge is a real pain.

I'm thinking about maybe:
- Document how to build the bridge jar's from github ?
- Publish on maven central (sonatype...) ? 
- Document some recipes using gradle, ivy or maven ? 
- Document tomcat install (linux/docker) ?

That would help to get rid off the shell scripts...

This is only directions we can take,  but let me know your ideas, especially what you want to do with the embed... Tomcat scope is more enterprise thing... The standalone may fit as well.

And if you have any experience, let me know it can help.

**Comment by belgattitude** [comment]
Just updated the [README.md](https://github.com/belgattitude/php-java-bridge/blob/master/README.md) for the build process on my php-java-bridge fork.

You can also see the 'old doc' for embedding, see the file INSTALL.J2EE and INSTALL.J2SE [here](https://github.com/belgattitude/php-java-bridge)... Will still take some time for me to figure out details.

**Comment by belgattitude** [comment]
Hi @nilsga ,

spend some time during holidays to study a bit the Java world and came up with a solution (wip)

See the [pjb-starter-gradle](https://github.com/belgattitude/pjb-starter-gradle) for updated info.

Also note that I've build some binaries [here](https://github.com/belgattitude/php-java-bridge/releases)

Feel free to use and contribute ;)

**Comment by nilsga** [comment]
Thanks, I'll have a look!
